import { expect, test } from '@playwright/test'
import { chapterBodyText, chapterQuotes, closeAllApps, configureLlm, dragSelectAcrossParagraphs, enableSelectionStore,
  importFixture, launch, slowDragSelectInChapter, waitForLocationsReady, waitForStableIndicator, type Harness } from './helpers'
import { closeAllFakeLlms, startFakeLlm } from './fake-llm'

test.afterEach(async () => { await closeAllApps(); await closeAllFakeLlms() })

async function openBook(h: Harness): Promise<void> {
  await enableSelectionStore(h)
  await importFixture(h)
  await h.page.getByTestId('book-card').first().click()
  await waitForLocationsReady(h)
}

async function noteSelected(h: Harness, text: string, index = 0): Promise<void> {
  await h.page.getByTestId('quote-chip').nth(index).hover()
  await h.page.getByTestId('quote-annotate').nth(index).click()
  await expect(h.page.getByTestId('annotation-input')).toBeEnabled()
  await h.page.getByTestId('annotation-input').fill(text)
  await h.page.getByTestId('annotation-submit').click()
  await expect(h.page.getByTestId('annotation-target')).toHaveCount(0)
}

async function notes(h: Harness) {
  return h.page.evaluate(async () => {
    const book = (await window.api.listBooks())[0]
    return window.api.listAnnotations(book.id)
  })
}

async function expectMarkersAtText(h: Harness): Promise<void> {
  await expect.poll(() => h.page.evaluate(async () => {
    const book = (await window.api.listBooks())[0]
    const stored = await window.api.listAnnotations(book.id)
    const rendition = (window as any).__readerRendition
    const views = rendition.views().all()
    return Array.from(document.querySelectorAll<HTMLElement>('.annotation-marker')).every((marker) => {
      const note = stored.find((item) => item.id === marker.dataset.annotationId)
      const view = views.find((item: any) => item.element.contains(marker))
      if (!note || !view) return false
      const rect = Array.from(view.contents.range(note.cfiRange).getClientRects())
        .filter((item: any) => item.width > 0 && item.height > 0).at(-1) as DOMRect
      const frame = view.iframe.getBoundingClientRect()
      const badge = marker.getBoundingClientRect()
      return !!rect && Math.abs(badge.left - frame.left - rect.right) < 2 &&
        Math.abs(badge.top - frame.top - rect.top + 6) < 2 &&
        getComputedStyle(marker.querySelector('sup')!).fontSize === '9px'
    })
  })).toBe(true)
  await expect.poll(() => h.page.evaluate(async () => {
    const book = (await window.api.listBooks())[0]
    const stored = await window.api.listAnnotations(book.id)
    const views = (window as any).__readerRendition.views().all()
    return views.every((view: any) => {
      const frame = view.iframe.getBoundingClientRect()
      const markers = Array.from(view.element.querySelectorAll('.annotation-marker')) as HTMLElement[]
      const lines = Array.from(view.element.querySelectorAll('.annotation-underline')) as HTMLElement[]
      return lines.every((line) => markers.some((marker) => marker.dataset.annotationId === line.dataset.annotationId)) &&
        markers.every((marker) => {
        const note = stored.find((item) => item.id === marker.dataset.annotationId)
        if (!note) return false
        const expected = Array.from(view.contents.range(note.cfiRange).getClientRects())
          .filter((r: any) => r.width > 0 && r.height > 0) as DOMRect[]
        const matched = lines.filter((line) => line.dataset.annotationId === note.id)
        return matched.length === expected.length && matched.every((line, i) => {
          const rect = line.getBoundingClientRect()
          return Math.abs(rect.left - frame.left - expected[i].left) < 2 &&
            Math.abs(rect.top - frame.top - expected[i].bottom + 1) < 2 &&
            Math.abs(rect.width - expected[i].width) < 2 && getComputedStyle(line).pointerEvents === 'none'
        })
      })
    })
  })).toBe(true)
}

test('悬停同时显示翻译和注释，本地提交及正文上标，不改正文和页码；重开可编辑删除', async () => {
  const h = await launch()
  await openBook(h)
  const before = await waitForStableIndicator(h)
  const body = await chapterBodyText(h)
  await h.page.getByTestId('chat-input').fill('保留对话草稿')
  await slowDragSelectInChapter(h)
  await expect(h.page.getByTestId('quote-annotate')).toBeHidden()
  await h.page.getByTestId('quote-chip').hover()
  await expect(h.page.getByTestId('quote-annotate')).toBeVisible()
  await expect(h.page.getByTestId('quote-translate')).toBeVisible()
  const quote = (await chapterQuotes(h))[0]
  await noteSelected(h, '本地笔记 <script>不可执行</script>')
  await expect(h.page.getByTestId('sidebar-tab-chat')).toHaveAttribute('aria-selected', 'true')
  await expect(h.page.getByTestId('chat-input')).toHaveValue('保留对话草稿')
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await expect(h.page.getByTestId('annotation-card')).toContainText('本地笔记')
  await expect(h.page.getByTestId('annotation-marker')).toHaveText('1')
  await expectMarkersAtText(h)
  expect(await chapterBodyText(h)).toBe(body)
  expect(await waitForStableIndicator(h)).toBe(before)
  const saved = (await notes(h))[0]
  expect(saved.quote).toBe(quote.text)
  expect(await h.page.evaluate(async () => window.api.listConversations((await window.api.listBooks())[0].id))).toEqual([])
  await h.page.getByTestId('sidebar-tab-chat').click()
  await expect(h.page.getByTestId('chat-input')).toHaveValue('保留对话草稿')
  await h.page.getByTestId('annotation-marker').click()
  await expect(h.page.getByTestId('annotation-input')).toHaveValue(saved.content)
  await h.page.getByTestId('annotation-input').fill('修改后的注释')
  await h.page.getByTestId('annotation-submit').click()
  await expect(h.page.getByTestId('annotation-card')).toContainText('修改后的注释')
  await h.page.getByRole('button', { name: '← 书架' }).click()
  await h.app.close()
  const restarted = await launch(h.userData)
  await enableSelectionStore(restarted)
  await restarted.page.getByTestId('book-card').first().click()
  await waitForLocationsReady(restarted)
  await expect(restarted.page.getByTestId('annotation-marker')).toHaveText('1')
  await restarted.page.getByTestId('annotation-marker').click()
  await expect(restarted.page.getByTestId('annotation-input')).toHaveValue('修改后的注释')
  expect((await notes(restarted))[0].id).toBe(saved.id)
  await restarted.page.getByTestId('annotation-delete').click()
  await restarted.page.getByTestId('confirm-note-delete').getByRole('button', { name: '取消' }).click()
  await expect(restarted.page.getByTestId('annotation-marker')).toHaveCount(1)
  await restarted.page.getByTestId('annotation-delete').click()
  await restarted.page.getByTestId('confirm-note-delete-yes').click()
  await expect(restarted.page.getByTestId('annotation-card')).toHaveCount(0)
  await expect(restarted.page.getByTestId('annotation-marker')).toHaveCount(0)
  await expect(restarted.page.getByTestId('annotation-underline')).toHaveCount(0)
  expect(await notes(restarted)).toEqual([])
})

test('先注释后文再注释前文，编号按原文顺序；字号/主题/侧栏重排不串位不重复', async () => {
  const h = await launch()
  await openBook(h)
  await dragSelectAcrossParagraphs(h)
  await noteSelected(h, '后面的注释')
  const later = (await notes(h))[0]
  await slowDragSelectInChapter(h)
  await noteSelected(h, '前面的注释')
  await h.page.getByTestId('sidebar-tab-annotations').click()
  const markers = h.page.getByTestId('annotation-marker')
  await expect(markers).toHaveCount(2)
  await expectMarkersAtText(h)
  await expect(markers.filter({ hasText: '2' })).toHaveAttribute('data-annotation-id', later.id)
  await expect(h.page.getByTestId('annotation-card').first()).toContainText('前面的注释')
  const original = await notes(h)
  const base = await waitForStableIndicator(h)
  await h.page.getByRole('button', { name: '放大字号' }).click()
  await waitForStableIndicator(h)
  await expect(markers).toHaveCount(2)
  await expectMarkersAtText(h)
  expect(await h.page.getByTestId('page-indicator').textContent()).not.toBe(base)
  await h.page.getByTestId('toggle-theme').click()
  await expect(markers).toHaveCount(2)
  await expectMarkersAtText(h)
  await h.page.getByRole('button', { name: '收起侧边栏' }).click()
  await waitForStableIndicator(h)
  await expect(markers).toHaveCount(2)
  await expectMarkersAtText(h)
  await markers.first().click()
  await expect(h.page.getByTestId('annotation-input')).toBeVisible()
  await h.page.getByRole('button', { name: '缩小字号' }).click()
  await waitForStableIndicator(h)
  await expect(markers).toHaveCount(2)
  await expectMarkersAtText(h)
  expect(await notes(h)).toEqual(original)
  await h.page.getByTestId('annotation-delete').first().click()
  await h.page.getByTestId('confirm-note-delete-yes').click()
  await expect(markers).toHaveCount(1)
  await expect(markers).toHaveAttribute('data-annotation-id', later.id)
  await expect(markers).toHaveText('1')
})

test('注释草稿跨标签/收起/翻页保留，换原文需确认，保存失败可重试', async () => {
  const h = await launch()
  await openBook(h)
  await slowDragSelectInChapter(h)
  await dragSelectAcrossParagraphs(h)
  await h.page.getByTestId('quote-chip').first().hover()
  await h.page.getByTestId('quote-annotate').first().click()
  await h.page.getByTestId('annotation-input').fill('不丢弃草稿')
  await h.page.getByTestId('sidebar-tab-chat').click()
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  await h.page.getByRole('button', { name: '← 书架' }).click()
  await h.page.getByTestId('confirm-note-leave').getByRole('button', { name: '取消' }).click()
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  const before = await waitForStableIndicator(h)
  await h.page.getByTestId('annotation-input').press('ArrowRight')
  expect(await waitForStableIndicator(h)).toBe(before)
  await h.page.getByRole('button', { name: '收起侧边栏' }).click()
  await h.page.getByRole('button', { name: '展开侧边栏' }).click()
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  await h.page.getByTestId('quote-chip').nth(1).hover()
  await h.page.getByTestId('quote-annotate').nth(1).click()
  await h.page.getByTestId('confirm-note-discard').getByRole('button', { name: '取消' }).click()
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  await h.app.evaluate(({ ipcMain }) => {
    const handler = (ipcMain as any)._invokeHandlers.get('annotations:create')
    let fail = true
    ipcMain.removeHandler('annotations:create')
    ipcMain.handle('annotations:create', (...args: unknown[]) => {
      if (fail) { fail = false; throw new Error('test disk failure') }
      return handler(...args)
    })
  })
  await h.page.getByTestId('annotation-submit').click()
  await expect(h.page.getByTestId('annotation-error')).toContainText('保存失败')
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  await expect(h.page.getByTestId('annotation-marker')).toHaveCount(0)
  await h.page.getByRole('button', { name: '下一页', exact: true }).click()
  await waitForStableIndicator(h)
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('不丢弃草稿')
  await h.page.getByTestId('annotation-submit').click()
  await expect(h.page.getByTestId('annotation-target')).toHaveCount(0)
  expect((await notes(h))[0].content).toBe('不丢弃草稿')
  await h.page.getByRole('combobox', { name: '注释范围' }).selectOption('book')
  await h.page.getByTestId('annotation-card').getByRole('button', { name: '定位注释 1' }).click()
  await expect(h.page.getByTestId('annotation-marker')).toBeVisible()
  await expectMarkersAtText(h)
})

test('当页筛选及全书编号，点击注释卡片可跨章节定位，不污染另一书', async () => {
  const h = await launch()
  await openBook(h)
  await slowDragSelectInChapter(h)
  await noteSelected(h, '第一章笔记')
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await h.page.getByTestId('toggle-toc').click()
  await h.page.getByRole('button', { name: '第二章' }).click()
  await waitForStableIndicator(h)
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(0)
  await slowDragSelectInChapter(h)
  await noteSelected(h, '第二章笔记')
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(1)
  await expect(h.page.getByTestId('annotation-marker')).toHaveText('2')
  await h.page.getByRole('combobox', { name: '注释范围' }).selectOption('book')
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(2)
  await h.page.getByTestId('annotation-card').first().click()
  await expect(h.page.getByTestId('annotation-marker')).toHaveText('1')
  await expectMarkersAtText(h)
  await h.page.getByRole('button', { name: '← 书架' }).click()
  await importFixture({ ...h, fixturePath: h.realisticFixturePath })
  await h.page.getByTestId('book-card').filter({ hasText: '真实排版' }).click()
  await waitForLocationsReady(h)
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(0)
  await expect(h.page.getByTestId('annotation-marker')).toHaveCount(0)
})

test('同章翻页只显示当页注释，字号重排后更新；全书卡片可用键盘定位', async () => {
  const h = await launch()
  await openBook(h)
  await slowDragSelectInChapter(h)
  await noteSelected(h, '第一页的注释')
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await expect(h.page.getByRole('combobox', { name: '注释范围' })).toHaveValue('page')
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(1)
  await h.page.getByRole('button', { name: '下一页', exact: true }).click()
  await waitForStableIndicator(h)
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(0)
  await h.page.getByRole('combobox', { name: '注释范围' }).selectOption('book')
  await expect(h.page.getByTestId('annotation-card')).toContainText('第一页的注释')
  await h.page.getByTestId('annotation-locate').focus()
  await h.page.getByTestId('annotation-locate').press('Enter')
  await expect(h.page.getByTestId('annotation-marker')).toBeVisible()
  await h.page.getByRole('combobox', { name: '注释范围' }).selectOption('page')
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(1)
  await h.page.getByRole('button', { name: '放大字号' }).click()
  await waitForStableIndicator(h)
  await expect(h.page.getByTestId('annotation-card')).toHaveCount(1)
  await expectMarkersAtText(h)
})

test('切换注释不打断聊天，注释内容不进 API 上下文，聊天清空选区不删除注释', async () => {
  const h = await launch()
  const fake = await startFakeLlm()
  fake.setMode('slow')
  await configureLlm(h, { endpoint: fake.url })
  await openBook(h)
  await slowDragSelectInChapter(h)
  await noteSelected(h, '仅本地注释：note-private-9173')
  await h.page.getByTestId('sidebar-tab-chat').click()
  await h.page.getByTestId('chat-input').fill('请解释当前内容')
  await h.page.getByTestId('chat-send').click()
  await expect(h.page.getByTestId('chat-stop')).toBeVisible()
  await h.page.getByTestId('sidebar-tab-annotations').click()
  await expect(h.page.getByTestId('annotation-card')).toContainText('note-private-9173')
  await expect(h.page.getByTestId('annotation-marker')).toHaveText('1')
  await expect.poll(() => fake.requests.length).toBe(1)
  expect(JSON.stringify(fake.requests[0].body.messages)).not.toContain('note-private-9173')
  await h.page.getByTestId('sidebar-tab-chat').click()
  await expect(h.page.getByTestId('message-assistant').last()).not.toHaveText('')
  await h.page.getByTestId('chat-stop').click()
  expect((await notes(h))[0].content).toContain('note-private-9173')
})

test('点击注释留在对话页，取消立即恢复发送及对话草稿；再次选择已注释原文也不切页', async () => {
  const h = await launch()
  await openBook(h)
  await h.page.getByTestId('chat-input').fill('原来的聊天草稿')
  await slowDragSelectInChapter(h)
  await h.page.getByTestId('quote-chip').hover()
  await h.page.getByTestId('quote-annotate').click()
  await expect(h.page.getByTestId('sidebar-tab-chat')).toHaveAttribute('aria-selected', 'true')
  await expect(h.page.getByTestId('chat-send')).toBeHidden()
  await h.page.getByTestId('annotation-input').fill('取消的注释')
  await h.page.getByTestId('annotation-target').getByRole('button', { name: '取消' }).click()
  await expect(h.page.getByTestId('annotation-target')).toHaveCount(0)
  await expect(h.page.getByTestId('chat-send')).toBeVisible()
  await expect(h.page.getByTestId('chat-input')).toHaveValue('原来的聊天草稿')
  expect(await notes(h)).toEqual([])
  await expect(h.page.getByTestId('annotation-underline')).toHaveCount(0)
  await noteSelected(h, '保存的注释')
  await slowDragSelectInChapter(h)
  await h.page.getByTestId('quote-chip').hover()
  await h.page.getByTestId('quote-annotate').click()
  await expect(h.page.getByTestId('sidebar-tab-chat')).toHaveAttribute('aria-selected', 'true')
  await expect(h.page.getByTestId('annotation-input')).toHaveValue('保存的注释')
  await h.page.getByTestId('annotation-target').getByRole('button', { name: '取消' }).click()
  await expect(h.page.getByTestId('chat-send')).toBeVisible()
  expect(await h.page.evaluate(async () => window.api.listConversations((await window.api.listBooks())[0].id))).toEqual([])
})
