import { expect, test } from '@playwright/test'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'
import { buildFixturePdf } from '../../scripts/make-fixture-pdf'
import { closeAllApps, importFixture, launch, waitForLocationsReady, waitForStableIndicator } from './helpers'

test.afterEach(closeAllApps)

test('旧书库升级后仅打开已保存位置即可更新百分比，不覆盖恢复位置', async () => {
  let h = await launch()
  await importFixture(h)
  await h.page.getByTestId('book-card').click()
  await waitForLocationsReady(h)
  await h.page.getByTestId('toggle-toc').click()
  await h.page.getByRole('button', { name: '第二章 那个夏天', exact: true }).click()
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress ?? 0)).toBeGreaterThan(0.2)
  const [saved] = await h.page.evaluate(() => window.api.listBooks())
  const profile = h.userData
  await h.app.close()
  const db = new DatabaseSync(join(profile, 'reader.db'))
  try { db.exec('ALTER TABLE books DROP COLUMN read_progress; PRAGMA user_version = 6') } finally { db.close() }
  h = await launch(profile)
  await expect(h.page.getByTestId('book-progress')).toHaveText('0%')
  await h.page.getByTestId('book-card').click()
  await waitForLocationsReady(h)
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(saved.readProgress)
  expect(await h.page.evaluate(async () => (await window.api.listBooks())[0].lastReadCfi)).toBe(saved.lastReadCfi)
})

test('EPUB 进度随正文保存，字号和侧栏不改变进度，读完/回翻/重启保持 100%', async () => {
  let h = await launch()
  await importFixture(h)
  await expect(h.page.getByTestId('book-progress')).toHaveText('0%')
  await h.page.getByTestId('book-card').click()
  await waitForLocationsReady(h)
  await h.page.getByTestId('toggle-toc').click()
  await h.page.getByRole('button', { name: '第二章 那个夏天', exact: true }).click()
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress ?? 0)).toBeGreaterThan(0.2)
  const progress = await h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)
  const before = await waitForStableIndicator(h)
  await h.page.getByRole('button', { name: '放大字号', exact: true }).click()
  await expect(h.page.getByTestId('page-indicator')).not.toHaveText(before)
  await waitForStableIndicator(h)
  expect(await h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(progress)
  await h.page.getByRole('button', { name: '收起侧边栏' }).click()
  await waitForStableIndicator(h)
  expect(await h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(progress)
  await h.page.getByRole('button', { name: '展开侧边栏' }).click()
  await h.page.getByTestId('toggle-toc').click()
  await h.page.getByRole('button', { name: '第三章 归途', exact: true }).click()
  for (let i = 0; i < 35; i++) {
    if ((await h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)) === 1) break
    await h.page.getByRole('button', { name: '下一页', exact: true }).click()
    await h.page.waitForTimeout(200)
  }
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(1)
  await h.page.getByRole('button', { name: '上一页', exact: true }).click()
  await waitForStableIndicator(h)
  await h.page.getByRole('button', { name: '← 书架', exact: true }).click()
  await expect(h.page.getByTestId('book-progress')).toHaveText('100%')
  await h.page.getByTestId('open-stats').click()
  await expect(h.page.getByTestId('stats-progress')).toHaveText('100%')
  await expect(h.page.getByTestId('stats-completed')).toHaveText('1 本')
  await expect(h.page.getByTestId('stats-book-progress')).toHaveText('100%')
  await expect(h.page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  const profile = h.userData
  await h.app.close()
  h = await launch(profile)
  await expect(h.page.getByTestId('book-progress')).toHaveText('100%')
  await h.page.getByTestId('open-stats').click()
  await expect(h.page.getByTestId('stats-completed')).toHaveText('1 本')
  await h.page.screenshot({ path: '/tmp/mowen-progress-stats-light.png', fullPage: true })
  await h.page.getByTestId('toggle-theme').click()
  await h.page.waitForTimeout(180)
  await h.page.screenshot({ path: '/tmp/mowen-progress-stats-dark.png', fullPage: true })
  await h.app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 600))
  expect(await h.page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await h.page.getByRole('button', { name: '← 返回书架' }).click()
  await h.page.getByTestId('delete-book').click()
  await h.page.getByTestId('confirm-delete-yes').click()
  await h.page.getByTestId('open-stats').click()
  await expect(h.page.getByTestId('stats-completed')).toHaveText('0 本')
  await expect(h.page.getByTestId('stats-progress')).toHaveText('0%')
})

test('PDF 固定页数进度：中间页不记读完，缩放不变，合并末页达到100%；无效输入不破坏保存', async () => {
  const h = await launch()
  const path = join(dirname(h.fixturePath), '进度.pdf')
  writeFileSync(path, buildFixturePdf())
  await h.page.evaluate(p => { (window as any).__E2E_FILES__ = [p] }, path)
  await h.page.getByTestId('pick-files').click()
  await h.page.getByTestId('book-card').click()
  await waitForLocationsReady(h)
  await h.page.getByRole('button', { name: '下一页', exact: true }).click()
  await expect(h.page.getByTestId('page-indicator')).toHaveText('第 2 / 3 页')
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(1 / 3)
  await h.page.getByRole('button', { name: '放大 PDF', exact: true }).click()
  await h.page.getByRole('button', { name: '← 书架', exact: true }).click()
  await expect(h.page.getByTestId('book-progress')).toHaveText('33%')
  await h.page.getByTestId('open-stats').click()
  await expect(h.page.getByTestId('stats-completed')).toHaveText('0 本')
  await expect(h.page.getByTestId('stats-book-progress')).toHaveText('33%')
  await h.page.getByTestId('stats-book').click()
  await waitForLocationsReady(h)
  await h.page.getByRole('button', { name: '加入下一屏', exact: true }).click()
  await expect.poll(() => h.page.evaluate(async () => (await window.api.listBooks())[0].readProgress)).toBe(1)
  expect(await h.page.evaluate(async () => {
    const [book] = await window.api.listBooks()
    try { await window.api.saveProgress(book.id, 'bad', NaN); return false } catch { return true }
  })).toBe(true)
  await h.page.getByRole('button', { name: '← 书架', exact: true }).click()
  await expect(h.page.getByTestId('book-progress')).toHaveText('100%')
})
