import { expect, test } from '@playwright/test'
import { closeAllApps, importFixture, launch, waitForLocationsReady } from './helpers'

test.afterEach(async () => { await closeAllApps() })

test('排版预设保存并在重开图书后恢复', async () => {
  const h = await launch()
  await importFixture(h)
  await h.page.getByTestId('book-card').first().click()
  await waitForLocationsReady(h)
  const initialTotal = Number(/\/ (\d+) 页/.exec((await h.page.getByTestId('page-indicator').textContent()) ?? '')?.[1])
  await h.page.getByTestId('toggle-typography').click()
  await h.page.getByTestId('typo-lineheight-2').click()
  await h.page.getByTestId('typo-margin-wide').click()
  await h.page.getByTestId('typo-font-sans').click()
  await expect(h.page.getByTestId('typo-lineheight-2')).toHaveAttribute('aria-pressed', 'true')
  await expect(h.page.getByTestId('typo-margin-wide')).toHaveAttribute('aria-pressed', 'true')
  await expect(h.page.getByTestId('typo-font-sans')).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(async () => Number(/\/ (\d+) 页/.exec((await h.page.getByTestId('page-indicator').textContent()) ?? '')?.[1])).toBeGreaterThan(initialTotal)
  await expect.poll(() => h.page.evaluate(() => Promise.all([
    window.api.getSetting('lineHeight'), window.api.getSetting('pageMargin'), window.api.getSetting('fontFamily')
  ]))).toEqual(['2', 'wide', 'sans'])
  await expect(h.page.getByTestId('page-indicator')).toContainText('第')
  await h.page.getByRole('button', { name: '← 书架' }).click()
  await h.page.getByTestId('book-card').first().click()
  await waitForLocationsReady(h)
  await h.page.getByTestId('toggle-typography').click()
  await expect(h.page.getByTestId('typo-lineheight-2')).toHaveAttribute('aria-pressed', 'true')
  await expect(h.page.getByTestId('typo-margin-wide')).toHaveAttribute('aria-pressed', 'true')
  await expect(h.page.getByTestId('typo-font-sans')).toHaveAttribute('aria-pressed', 'true')
})

test('快捷键帮助、改键和修饰键隔离', async () => {
  const h = await launch()
  await importFixture(h)
  await h.page.getByTestId('book-card').first().click()
  await waitForLocationsReady(h)
  await h.page.keyboard.press('?')
  await expect(h.page.getByTestId('shortcuts-help')).toBeVisible()
  await h.page.getByTestId('shortcut-input-toc').fill('n')
  await h.page.getByTestId('shortcut-input-bookmark').fill('m')
  await h.page.getByTestId('shortcut-save').click()
  await h.page.getByTestId('shortcuts-close').click()
  await h.page.keyboard.press('Control+n')
  await expect(h.page.getByTestId('toc')).toHaveCount(0)
  await h.page.keyboard.press('n')
  await expect(h.page.getByTestId('toc')).toBeVisible()
  await h.page.keyboard.press('n')
  await expect(h.page.getByTestId('toc')).toHaveCount(0)
  await h.page.keyboard.press('m')
  await expect(h.page.getByTestId('bookmark-toggle')).toContainText('已加书签')
})
